### ISSUE TITLE
大家觉得该知乎问题中最值得分享给大家的答案是什么？

### ISSUE THREAD

**Issue by miniflycn** [FE-star/2018.6#10]
https://www.zhihu.com/question/35737930

请回复～～thx

**Comment by if2er** [comment]
把答案差不多刷了一遍：

推荐这个比较中肯的回答
- 为什么一些公司招前端不想要培训班出来的人？ - 林志鹏的回答 - 知乎
https://www.zhihu.com/question/35737930/answer/135803741

以及这个回答的前半部分：
- 为什么一些公司招前端不想要培训班出来的人？ - 欲三更的回答 - 知乎
https://www.zhihu.com/question/35737930/answer/274715528

**Comment by Fridolph** [comment]
楼上的同学速度好快。我这里再补充个： 

* 为什么一些公司招前端不想要培训班出来的人？ - 张小河的回答 - 知乎
https://www.zhihu.com/question/35737930/answer/116146170

**Comment by aoxiaoqiang** [comment]
刚才看到这个issue，刚把帖子 “为什么一些公司招前端不想要培训班出来的人？” 大致看了一下，这里我谈谈自己的理解哈。知乎的这个问题主要是让大家认识到学习过程中需要培养自己的不单是技术，更多的是学习知识的一种能力以及对待学习的一种态度。

1. 公司不想招培训出来的主要的点不是在培不培训上，主要的点在于求职者本人有没有一种自我主动学习新知识、处理问题独立思考和解决问题的思路和能力。而现今的绝大多数培训班几乎都是速成班几个月就把所有知识传递给学员，最后再进行面试技巧等包装就去找工作。这种填鸭式教育，弱化了很多人(不是所有热哈)独立思考的能力。

2. 我之所以提到态度是觉得因为一些培训的学员是从其他行业可能是觉得搞IT待遇比其它行业要好，甚至还有不少0基础班。不乏一些这些学生就是纯粹以找份工作为目的那一份相对高的工资，进行短短几个月的培训。最终可能对于培训的技术方方面面都能说会道，实践也就是培训中做的几个项目。在真正的技术应用和对知识横向纵向自我探索衍生的能力很弱。

3. 培训不培训不是问题的根本点，企业有这粗略的过滤也是想给那些正真热爱技术、真正热爱技术钻研技术的人更多的机会，而不是找那些以培训来的速成技术找份好工作的人更多的机会。

4. 在技术的学习上要不断的学习新的技术和知识才能创造出更新更优秀的产品。

**Comment by asd2766** [comment]
为什么不喜欢从培训班出来的人，虽然我也是从培训班出来的，我个人理解是： 
1. 培训班出来的人普遍基础很差（自身经验）！！！而且自学能力不强
2. 很多人都眼高手低，简历包装过度
3. 我刚参加培训班的时候刚好是培训班刚好还未特别泛滥的时候，那个时候大家还没有那么排斥培训班出来的人，我参加工作后一年之后培训班就开始泛滥了，很多老师都会让你在简历上写上有3年工作经验，而且会伪装自己的工作经验，并且薪资要求会比较高，这就出现了能力与薪资不符的情况，导致后面很多招聘上就写上了不要培训班或者要3年工作经验以上的人

**Comment by zhuanyongxigua** [comment]
培训班的问题我就不讨论了。众多的回答中会对我的实践有指导意义的是[欲三更](https://www.zhihu.com/question/35737930/answer/274715528 )的回答中的一部分：

1. 搞清楚什么是技术，什么是工具。

   > 什么是技术？技术是你解决问题的能力。会使用工具不叫技术，会使用工具解决问题才叫技术。

   这一点我就理解成工具的使用场景了。

   > 要做到会使用工具解决问题，必须做到两点，**第一是，你要懂工具，第二是，你要懂问题。** 

   回答中举了React的例子，问了一系列的问题：“React到底用来解决什么问题？ ”，“为什么React会出现 ”，“出现React之前前端应用是如何开发的，低效点在哪里 ”，“针对这些问题，React做了哪些针对设计？”。

2. 代码量并不能代表编程能力，要想办法知道什么是“好代码”。
   较普遍的现象：代码量大，但是质量不高，潦草，各种边界情况处理不完备，逻辑漏洞，缺乏设计。
   出现这个问题的原因：不知道什么样的代码是合理的。
   这个也是我之前一直在想的问题，我不知道“好代码”长什么样，所以在业务熟练了之后，成长就非常缓慢了。

3. 认真阅读文档，完善知识体系。
   较为普遍的现象：仅仅满足于“work”，在网上复制粘贴代码不加审视，遇到问题就动用搜索引擎，找到答案也不求甚解，甚至不验证多种情况下是否能解决问题。长此以往，脑袋里面的知识结构完全不成体系，堆积了大量来历可疑，没有来龙去脉，不懂前因后果，仅仅是勉强work的二手野路子方法。 
   这种现象带来的问题：举一反三的能力差，并且缺乏预见性。
   这两点是资深工程师重要的技能。

   

对于这三个问题，答主也给了他的方案，“轻培训，半自学”。

**Comment by Yatoo2018** [comment]
上面的各位大佬讲的都非常到位，特别是@zhuanyongxigua的说的。
我对培训这个事情的认知也是和大家一样，不过，还是觉得要自己动手，不动手的话，培训老师教的再好，也会是左耳朵进，右耳朵出，今天看，明天忘。
最终就会怨这怨那，反正就不从自身找问题。
归结到底还是人性的问题。

**Comment by CR7LOVE** [comment]
1. 为什么一些公司招前端不想要培训班出来的人？
其实对公司来讲只是一个成本问题而已。
如果面试者技术好，公司肯定是想要的，如果不好，公司肯定不想要。
既然一些公司不想要培训出来的人，就是说公司觉得成本太高，那就意味着培训（**初级**培训）出来的人中有相当比例的人技术不好，导致公司心累，遂不想招。
2. 为什么培训（**初级培训**）出来的人中有相当比例的人技术不好？
什么人会去**初级**培训？
一部分是大学快毕业的，这些同学可能是软件专业，也可能不是。
另一部分，是出于各种原因，在没有软件行业的基础下，从其他行业想转此行的。
这两种类型，除了本身是软件专业和自学能力特别强的人，相信其他人培训出来后水平肯定是不好的，而且很多基础和原理的部分肯定是不清楚的。这个就是导致普遍技术不好的原因。
3. 应当怎样做
如果1,2都明白了，也就无所谓培训，无所谓自学，这不重要。找到一种适合自己的高效的方式方法，努力提高就是了。最近的感受是，广涉猎，多动手，多总结，独立思考，形成体系。

**Comment by CarisL** [comment]
1.有很多培训班也是填鸭式教学，解决问题的能力可能还有很高的提升空间。
2.培训班出来的水平参差不齐，并没有一个统一的考核标准。
3.过度的包装，降低了简历的真实性。
