### ISSUE TITLE
第三节课问题收集

### ISSUE THREAD

**Issue by if2er** [FE-star/2018.6#11]

**Comment by if2er** [comment]
老师，闭包和词法作用域为什么不需要讲？因为在js中不需要了解到这么深吗？

**Comment by if2er** [comment]
关于那个`bind: undfined`的问题：

我是这么理解：
1、声明提升var obj
2、到了初始化阶段，会obj={say: fn}，这个时候fn会执行吗？我理解的不会。
3、obj.say()，执行fn，此时obj不是有赋值了吗？

参照demo：
```javascript
var obj={
	say: function () {
		return obj;
	}
}
obj.say(); // {say: fn}
```

为什么会出现undefined的情况呢？

**Comment by zhangchch** [comment]
练习4中test.js的bind undefined测试用例的执行顺序的理解：
1、变量申明, var obj
2、变量赋值的时候遇到自执行函数，先执行自执行函数后，在赋值，也就是说，先执行
```
say: function () {
          function _say() {
            this.should.equal(null)
          }
          return _say.bind(obj)
        }()
```
执行完后，
```
say: function _say(obj) {
     this.should.equal(null)
}
```
3、往下执行，执行obj.say()
4、执行_say(obj)
此时obj为何是undefined ？？？？？

**Comment by asd2766** [comment]
es5 中的继承需要深入了解些么？我发现我对这个概念有点模糊

**Comment by asd2766** [comment]
es5 中我看到 原型继承的时候，发现我们在将子类原型指向父类之后，需要将构造器重新指回子类；
比如： 
function Animal() {}
function Cat() {}
Cat.prototype = new Animal();
// Cat.prototype.constructor = Cat; // 这里需要重新指回 Cat，不然会导致继承链紊乱，摘自阮一峰博客

var cat1 = new Cat(); // 后面建的实例，上一行如果没写，constructor 都将是指向 Animal

我比较好奇继承链紊乱会怎么样？ 会造成什么用的后果？

**Comment by zChanges** [comment]
> 先创建实例，在修改原型，会不起作用，是为了创建实例后不让随意修改？为什么这么做呢
```
function Person () {}
var friend=new Person();
Person.prototype={
    constructor:Person,
    name:'Nicholas',
    age:29,
    job:'Software Engineer',
    sayName:function () {
        console.log(this.name);
    }
}
friend.sayName(); //error
```

**Comment by if2er** [comment]
@zChanges 你把原型链画出来就明白了，先创建实例，那实例的__proto__指向的是默认的Person.prototype，但是后面你把其重新赋了一个值相当于重写了原型对象，但是之前创建的实例并没有指向他，只有后创建的实例才会指向你重写后的原型对象。

见《js红宝书》

**Comment by if2er** [comment]
![image](https://user-images.githubusercontent.com/3774016/41947016-baf33ae4-79e7-11e8-9003-8e333c3f73e7.png)
创建实例，实例的__proto__会指向当时构造函数的原型对象

**Comment by yorts52** [comment]
@if2er 这图能不能旋转一下？颈椎病又要犯了

**Comment by if2er** [comment]
@yorts52 
我转了，没成功，哈哈哈。老师正好动动脖子，运动下。

另外，刚完成homework2，是参照着答案完成的，觉得db和test存在严重耦合，和看到题目时思路冲突了，不知道是我想偏了，还是有更好的解法。 [https://github.com/FE-star/homework2/pull/60](https://github.com/FE-star/homework2/pull/60)

**Comment by Fridolph** [comment]
老师好，能不能说一下**跨域** 及 跨域涉及到的**安全**问题，因为面试时被问到答得不太好，我列了以下几个问题

1. jsonp跨域请求的并发问题，假设有a,b,c,d 4个同时请求，怎么判断服务端返回的是哪个数据的？
2. jsonp怎么限制其他域名访问，一些具体的方案
3. 开启跨域头 比如 `Control-Access-Allow-Origin: *` 涉及到的一些安全问题，怎么做更好些

**Comment by yorts52** [comment]
‮ @if2er 我来转吧

**Comment by yorts52** [comment]
@Fridolph 安全相关的问题后面会专门讲

> jsonp跨域请求的并发问题，假设有a,b,c,d 4个同时请求，怎么判断服务端返回的是哪个数据的？

问这个问题说明你没有真正理解 jsonp 的原理，先理解原理（可以写代码试试加深印象）

**Comment by if2er** [comment]
啊6点有作操个这你，师老 [25stroy@](https://github.com/yorts52)

**Comment by Fridolph** [comment]
@yorts52  老师请看下我的demo
https://codepen.io/fridolph/pen/OEBXBp

jsonp请求是按下面的顺序添加的

1. testjsonp
2. foo
3. MusicJsonCallback
4. GetListJsonCallback

执行后得到的顺序却是：

1. MusicJsonCallback
2. foo
3. GetListJsonCallback
4. testjsonp

我看了下 network里 请求顺序和添加是一致的，但得到结果却不同~ 那控制 执行显示顺序 是不是可以走 回调（Promise async那套了呢？）

**Comment by yorts52** [comment]
@Fridolph

我简单改造了一下，参考: https://codepen.io/yorts52/pen/GGYmXL
另外，MusicJsonCallback 比较坑爹，不支持自定义 callback

---

jsonp 一般都是异步的，理论上不应该要求 callback 按顺序执行，如果遇到这种情况，要思考一下是否解决方案本身就有问题

**Comment by yorts52** [comment]
@Fridolph 突然想到一个点，虽然 MusicJsonCallback 比较坑爹不支持自定义 callback，但是这样做也是有一个好处的，就是可缓存，从结果上也证明了这一点，所以每次都是 MusicJsonCallback 第一个返回

**Comment by asd2766** [comment]
老师我在写 es5 中的继承的时候，发现了几个问题，可以帮我解答下么？
https://github.com/asd2766/execrise5/blob/11e47cd1a142031bd699850d2ca41241cad68de2/lib/base.es5.2.js

https://github.com/asd2766/execrise5/blob/11e47cd1a142031bd699850d2ca41241cad68de2/lib/base.es5.5.js

**Comment by if2er** [comment]
老师，在浏览器中**setTimeout、setInterval和匿名函数执行时的当前对象是全局对象window**，是不是可以理解为所有的异步过程中函数执行的当前对象都是全局对象window。

**Comment by if2er** [comment]
声明提升不会被**条件判断**所控制，那什么情况下会被控制呢？
之前一直以为在ES6之前，js中没有块级作用域，只有全局和函数作用域，那么类似if，while等都应当属于全局作用域，都应该会进行声明提升，但是下述代码却报错了。所以希望老师详细讲解一下这块的原理和执行过程。
```javascript
foo();  //  TypeError: foo is not a function
while(false){
	function foo() {
		console.log(1);
	}
}
```
```javascript
foo();  //  TypeError: foo is not a function
while(1){
	function foo() {
		console.log(1);
	}
}
```

**Comment by if2er** [comment]
另外，es5继承里用到的merge方法可以用Object.assign()代替吗？我看Object.assign方法也是讲传递对象“非枚举、自身”的属性merge到target上，应当符合我们merge方法的功能吧。

**Comment by zhulin2609** [comment]
@if2er 其实讲`
this`和声明提升的时候是有讲到作用域的。
其实单独讲作用域会有一点干，理解作用域掌握以下几点就ok：
1. 函数作用域和块级作用域的定义，这些有很多资料了，要注意的可能就是`try catch`的catch分句。let和const的块级作用域可以自己下去看，课上讲不完的。
2. JS是词法作用域，书写代码时，作用域链、作用域与变量之间的绑定关系就被确定了。变量定义在哪一级作用域，就只能在该级作用域被访问和修改。
3. 遍历嵌套作用域链的规则：引擎从当前的执行作用域开始查找变量，如果找不到，就向上一级继续查找。当抵达最外层的全局作用域时，无论找到还是没找到，查找过程都会停止。
4. 理解ReferenceError同作用域判别失败的关系，可以自己下去了解RHS和LHS。
5. with：也可以改变当前的作用域，可以将一个没有或有多个属性的对象处理为一个完全隔离的词法作用域，因此这个对象的属性也会被处理为定义在这个作用域中的词法标识符，但是被with块中`var`和`不带var自动创建全局变量（对象没有该属性）`不受影响，但是with和eval一样都会破坏引擎在编译阶段对代码的性能优化，在严格模式下with还不能用，而且表现真的有点奇怪，所以就不浪费时间讲了。

所谓“闭包”，就是可以在定义变量的作用域之外，访问到这个变量所存储的值（并不能直接访问该变量哦~）。那理解了作用域，闭包其实就没什么好讲的了。一般都是将函数类型的值进行传递，来形成所谓的“闭包”，被传递的函数依然保持对定义它的作用域的引用，这个引用就是“闭包”。

**Comment by zhulin2609** [comment]
@zhangchch 恩，可以这么理解，因为`=`操作符的执行顺序是先执行`=`右边的代码。

**Comment by zhulin2609** [comment]
@if2er 可以用Object.assign()代替，但是es5没这个api
