### ISSUE TITLE
第四节课预习

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#12]
### 正则表达式
+ https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Regular_Expressions
+ https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp
+ 熟悉以下概念
   > 元字符
   > 量词
   > 分组和引用
   > 转义
   > 零宽断言
   > 贪婪 & 惰性
+ 完成以下练习
   > https://github.com/FE-star/exercise5
   > https://github.com/FE-star/exercise6
   > https://github.com/FE-star/exercise7
+ 推荐书籍: https://book.douban.com/subject/2154713/ 重点是前五章
+ 另外可以了解一下 [ES2018](https://medium.com/front-end-hacking/javascript-whats-new-in-ecmascript-2018-es2018-17ede97f36d5) 在正则方面有哪些扩展

### 模块化
+ 回顾一下模块化的历史：http://huangxuan.me/js-module-7day/#/
+ 围观一下showcase：https://github.com/FE-star/showcase3

### 扩展知识（非预习内容）
+ 上古大神“张云龙”的一些模块化和工程的思考，虽然有些古老了，但是很多问题是一些通性问题：https://github.com/fouber/blog

**Comment by yorts52** [comment]
### 标准
> 今天在群里看到有人在讨论标准，这里补充一点关于标准的一下资料（非预习内容）：

+ 这里说的标准一般是指[ECMAScript](https://naturefeng.github.io/2016/09/22/%E5%A6%82%E4%BD%95%E6%9B%B4%E5%A5%BD%E7%9A%84%E4%BA%86%E8%A7%A3ECMAScript/) 的标准
+ 流传最广也是最众所周知的就是 [262](http://www.ecma-international.org/publications/standards/Ecma-262.htm)
+ 此外还有 402 404 414，参考：http://www.ecma-international.org/publications/standards/Standard.htm
+ 定制这个标准的组织是 [tc39](https://github.com/tc39)
+ 最新的提案可以参考 https://github.com/tc39/proposals 和 https://prop-tc39.now.sh/

### 源码实现
+ https://github.com/v8/v8
+ https://github.com/Microsoft/ChakraCore
+ https://github.com/mozilla/gecko-dev
