### ISSUE TITLE
第四节课问题收集

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#13]

**Comment by asd2766** [comment]
除去angular，vue，react前端框架，如果自己写的时候一般是怎么处理模块化？

**Comment by yorts52** [comment]
@asd2766 

目前来说，大多数前端框架（脚手架）模块化都是基于 webpack 做的，可以考虑 webpack，后续 @zhulin2609 会专门讲 webpack

另外，如果需要用到最新的 ES 特性，一般都是通过 babel 转成 ES5（大多数浏览器都支持ES5）

**Comment by if2er** [comment]
`/^(?!([img])(?=.*\1))[img]+$/.test('igi')`这个执行过程可以详细的解释一下吗？
看MDN上对零宽断言的定义是：
`x(?=y) `匹配'x'仅仅当'x'后面跟着'y'.这种叫做正向肯定查找。
但是上面`(?!([img])(?=.*\1))`如果前面的x理解为`^`的话就是说**匹配开头，并且后面不跟着[img]中任何一个**，但是这种在正向否定断言语法中又插入了一个正向肯定语法：(?=.*\1)，这里也不符合MDN里介绍的标准断言语法，所以这一块自己理解起来还是有点懵，希望老师能详细指点一下。

**Comment by miniflycn** [comment]
@if2er 
利用工具试试：https://regexper.com/

![image](https://user-images.githubusercontent.com/2239584/42168256-137ec656-7e43-11e8-8c13-d9517a52dee7.png)

**Comment by if2er** [comment]
@miniflycn 谢谢老大，这个工具很赞

**Comment by if2er** [comment]
@yorts52 老师，`/^(?!([img])(?=.*\1))[img]+$/`这个正则只能保证后面的字符不与开头的第一个字符重复，类似`igg`、`igmg`这种后面重复的就也通过了。我分析是因为断言只占据了开头位置往后看，所以为了保证后面都不重复的话，断言应该在每个位置上都应该有，所以就想着把断言放在循环中，即类似这种`/^(?!  )*$/`，这样就能保证断言在匹配的每个位置上都会进行判断，因此最终构造的正则如下：
```javascript
/^((?<char>[img])(?!.*\k<char>))*$/
或者
/^((?[img])(?!.*\2))*$/
```
但是这里还存在一个问题，因为上面语法兼容性不好的时候必须使用下面的语法格式，但是不知道为什么是`\2`，因为发现`\1`是不符合需求的。

其实，这里就引申出来的问题就是，**当括号嵌套时，怎么判断记住的是第几个？**

**Comment by Yatoo2018** [comment]
@if2er 
```
/^(([img])(?!.*\2))+$/
```
理了下，这个结果很完美。
不过从这里能看到实现这种不重复的，宾生老师提供的实现思路非常重要。

**Comment by yorts52** [comment]
上课的时候写的确实还是有问题，用例本身就太少了，我更新了一下 [showcase](https://github.com/FE-star/showcase13/commit/4f0628c68c5f16663f132524f2af1aa68c300831)，新增了几个用例并更新了一下正则

**Comment by yorts52** [comment]
看到大家对这个这么感兴趣，挺好的，这个例子用来学习 `零宽断言` + `分组` + `引用` 都是不错的，这个正则正是三者的结合。

但是我们平时写代码还是要考虑代码的可读性以及性能问题，正则的可读性一般不太好，没有充分的测试用例很容易被坑，有一句话是这么说的 `学会了用锤子，满世界找钉子`，学会了正则也不要觉得什么都应该用正则来解决，这个问题更好的解决方案应该是写一个函数。我在这个 [showcase](https://github.com/FE-star/showcase13/commit/f468acd71f4e8aa7e677d90816c3d038c58498db) 添加了一个函数的实现和 benchmark，这是我电脑运行的结果：

![image](https://user-images.githubusercontent.com/863697/42231251-a036d860-7f1d-11e8-9132-ecf0775c089a.png)

从运行的结果上看，通过函数来处理性能和可读性都会好一点（当然代码也多了不少，写好正则确实能省不少代码）

**Comment by if2er** [comment]
@yorts52 嗯嗯，刚才还在想这种循环的正则性能是不是会很不好，没想到老师就比较了。每种技术都有优劣，关键看了解原理后如何选择，学习了。谢谢老师
