### ISSUE TITLE
一次还没开始就结束的面试分享

### ISSUE THREAD

**Issue by if2er** [FE-star/2018.6#14]
上周五有位大厂的大神向我要简历，心想着就体验一把吧，没想到面试下来不到10min就结束了，不过还是有收获。

## 面试过程
1、自我介绍
> - 12年开始接触前端，传统
> - 毕业1年左右
> - 中间接触过一些项目，但用的不深

2、引申如何学习前端知识？
> - 基础 和 业务
> - 基础学习，着重记录和总结
> - 框架，视频 + 文档

3、webpack模块懒加载原理？
> 一脸懵...完全没答上来

4、介绍一下React？
> 组件、虚拟DOM、JSX => 评价说理解比较片面

5、挂……

## 感受
其实问我的两个问题我毫无招架之力，本来以为会从基础入手的，哈哈哈。问的都是现代前端的原理。

## 补充
我抓紧问：传统前端和当今大前端的学习？
> 原问题介绍是这样的，我认为自己传统前端的基础其实也还很薄弱，很多东西虽然掌握了，但是老感觉自己没学到位。再加上现代大前端的趋势，模块化、工程化等等，感觉学起来更是懵，很多高大上的概念。感觉自己啥也不会了，针对这两者的学习，有什么建议吗？

答：**建议去看看webpack的源码，里面其实用的都还是那些东西，其实看了源码就能够把传统前端的很多东西串起来。**

get.

**Comment by miniflycn** [comment]
现在如果再回答这些问题能回答吗？

**Comment by if2er** [comment]
@miniflycn 会答一点，不会完全不知道了。至少知道人家问的是啥
