### ISSUE TITLE
第六节课问题收集

### ISSUE THREAD

**Issue by zhulin2609** [FE-star/2018.6#20]

**Comment by if2er** [comment]
前端模板的发展历史是否就能够代表前端的发展史。其实当前React和Vue也并不是最佳的解决方案，就像课上提到的面向未来的Web Component，如果从标准层面就已经支持了组件化（本质上也是前端模板更深入的应用，将html、css、javascript封装在了一起）。所以从这个角度去理解和学习前端，是不是思路上就会连贯许多...

**Comment by asd2766** [comment]
背景：除了vue，未在其他项目中应用过webpack，也未做过项目构建
问题：在一个项目是否需要webpack，需要在哪些方面？或者说webpack的应用场景有哪些？

**Comment by if2er** [comment]
webpack中的loader和plugin怎么用，entry、output和mode都能理解，前两者理解的不是很深，而且不知道啥时候该用什么？具体业务场景下怎么写loader和plugins的配置，都有相应的文档吗？

**Comment by snowfighting** [comment]
CommonsChunkPlugin具体要怎么使用？它既可以提取代码的公共部分，也可以提取entry中定义的vendor(比如entry: {vender: ['echarts','jquery']})到一个单独的文件，感觉有好几种用法，具体怎么使用呢？
