### ISSUE TITLE
第七节课问题收集

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#21]

**Comment by zhangchch** [comment]
渲染引擎取得内容之后，在进行渲染的时候，
1、先解析html构建dom树，同时解析css构建规则树
2、通过第一步生成的dom树和规则树构建render树
3、布局render树
4、根据布局绘制，最后显示页面

可是在进行首屏优化的时候，第一步的dom树还没完全被解析成功，就开始渲染页面了，
造成首屏出现的时间比dom解析完成的时间还早，这是如何实现的呢

**Comment by zhuanyongxigua** [comment]
资源的缓存时间是如何确定的？比如3分钟，1小时，1个月，1年，这些数是怎么来的？是根据经验随便给的吗？

**Comment by asd2766** [comment]
如果是多tab页的网站，会不会tab多了之后导致卡顿？会的话有什么优化方法么？
