### ISSUE TITLE
第九节课问题收集

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#25]

**Comment by CR7LOVE** [comment]
老师，我想知道为什么要学node，因为平时也就用来装包和写npm scripts，暂时没发现有别的用途。那学node是用来了解后端么？

**Comment by asd2766** [comment]
1. 像上课提到的XSS，CSRF 这些攻击是需要前端做防护措施还是后端需要，或者前后端都需要做防护。
2. 有没有什么监控这些攻击的手段？如何知道网站被攻击了？
3. node 的主要应用场景是什么？仅仅是做为前后端的中间层？还是有什么其他的应用场景？
