### ISSUE TITLE
第十节课问题收集

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#26]

**Comment by asd2766** [comment]
1. 如果node作为中间件来使用，大部分情况下是否还是有很多会用到node来渲染html，如果是的话那么这个跟以前jsp模式有什么区别么？
2. node 如果要跟后端进行数据交互是通过 axios 这类的http请求库来进行请求数据么？是否有需要直接对数据库进行操作的情况？
3. 前端请求都可以通过 ajax 这类请求来请求 node 服务么？
4. egg.js 是在 koa 基础上进行了封装，那么是否直接使用 egg.js 是否会比较贴合或者说简单的去构建服务？
5. 老师我想问下一般node部署到服务器上，是不是 前端，node，后端 会部署在3个不同的域名上？
