### ISSUE TITLE
第十一节课问题收集

### ISSUE THREAD

**Issue by zhulin2609** [FE-star/2018.6#28]

**Comment by if2er** [comment]
凭着自己对于 React 的粗浅理解，很重要的一点在于其状态管理和数据驱动的思想和编程方式，一个页面，本质上就是对于状态和数据的管理，加上内部高效率的 DOM 更新方式（虚拟 DOM），使得更改状态后就能立即最小且高性能的更新 UI（DOM）。

但是我的一个疑惑点在于，其实很多操作还是需要依赖 DOM 的，例如以下场景：
- 表单操作（input 等表单元素的自带特性，例如 checkbox、radio、form 的 submit）
- 滚动相关，需要获取元素的位置信息

以上，都是需要 DOM 强依赖的操作，那在 React 中一般都是如何完美解决的？是否和最初的设计理念有矛盾？

**Comment by weijie9520** [comment]
想问下react 服务端渲染怎么做， 或者有什么好的例子或方案参考下

**Comment by zhulin2609** [comment]
@weijie9520 
https://github.com/zeit/next.js
同构的话参考这两篇：https://www.jianshu.com/p/3502c13dd463 https://www.cnblogs.com/liuliliuli2017/p/6838690.html

**Comment by zhulin2609** [comment]
```
location /index.html {
     proxy http://100.1.1.xxx:8080
     error_page 404 500 501 502 503 504 @errpage;
}
@errpage {    
    access_log logs/access.log maintry;    
    proxy_pass /data/sites/www/;
}

```
