### ISSUE TITLE
第二节课问题收集

### ISSUE THREAD

**Issue by loskael** [FE-star/2018.6#3]

**Comment by yorts52** [comment]
@zhangchch 

参考 https://www.cnblogs.com/lovesong/p/5272752.html 和 exercise17 的例子

１、发布/订阅模式与观察者模式的区别？
> 发布/订阅模式有一个 `调度中心`，所有的事件经过调度中心，直接到了订阅者（类似微博发布和粉丝订阅）  
> 观察者模式则是拆分出目标（Subject ）和观察者（ObserverList）两个类，分别做管理（有依赖关系）

![image](https://user-images.githubusercontent.com/863697/41200481-a1a6b448-6cd7-11e8-887a-90b9e510adab.png)

2、ObserverList这个类的目的？
> 这个类存在的目的是对观察者的管理，课上我曾经说过这里可以做一些权限控制之类的处理，放在实际应用中就是我可以在这个类里面加一些鉴权的逻辑，如果鉴权不通过（表现为调用 add 失败）则表示你不能观察改事件的变化，另外也可以通过调整 count 和 get 的返回结果来达到对事件的过滤和灰度  

> 另外就是可以通过调整 notify 达到节流和防抖的效果，这个对于频繁发生的事件很有必要

**Comment by yorts52** [comment]
另外，没必要纠结 `发布/订阅模式` 和 `观察者模式`的区别，事实上，这两个模式非常相似，甚至可以相互替换，至于是否需要将 Subject 和 ObserverList 抽象成两个类来处理，答案也不是必须的，软件工程很重要的一点就是代码要怎么拆分，要拆分到什么粒度都是没有标准答案的。

**Comment by asd2766** [comment]
问题: 
我发现这两个模式有点模糊, 有些blog上说这两个模式是同一个, 但是有些blog上确说是两种模式, 这个让我很迷惑, 比如老师发群里的 http://design-patterns.readthedocs.io/zh_CN/latest/behavioral_patterns/observer.html, 
还有就是  JavaScript Design Patterns 这本书里面却提到了两个模式的区别
![image](https://user-images.githubusercontent.com/16233393/41201615-975750fe-6ced-11e8-99c3-d895fdd9ef85.png),
有大神可以解答下么?

**Comment by Fridolph** [comment]
@asd2766  https://www.cnblogs.com/lovesong/p/5272752.html 这篇文章你可以参考下，也是上课前看到的，可结合老师的资料一起参考

### 观察者模式

目标和观察者是基类，目标提供维护观察者的一系列方法，观察者提供更新接口。具体观察者和具体目标继承各自的基类，然后具体观察把自己注册到具体目标里，在具体目标发生变化时，调度观察者的更新方法。
![Observer](./Observer.png)

### 发布订阅模式 
订阅者把自己想订阅的事件注册到调度中心，当该事件触发时，发布者发布该事件到调度中心（顺带上下文）有调度中心统一调度订阅者注册到调度中心的处理代码。

## 两个模式间区别

* 两者最大的区别是调度的地方

虽然两种模式都存在订阅者和发布者（具体观察者可认为是订阅者，具体目标可认为是观察者），但是观察者模式是由具体目标调度的，而发布/订阅模式是统一由调度中心调度的。所以观察者模式的订阅者和发布者之间是存在依赖的，而发布/订阅模式则不会

* 两种模式都可以用于松散耦合，改进代码管理和潜在的复用

---

> 就像老师回答的，`没必要纠结区别`， 因为拆分就没有标准答案，使用观察者还是发布订阅需要看具体场景，因地制宜吧

**Comment by miniflycn** [comment]
good，大家尽可能在issue提问哈～这样易于沉淀

**Comment by if2er** [comment]
老师，异步场景下this的指向，如果不是明确指定的话，是不是默认就是window？就像js高程里讲解setTimeout和setInterval一样。因为其执行具有全局性。

**Comment by if2er** [comment]
另外，想问下老师，我把[课程内容](https://github.com/if2er/blog/blob/master/md/zhenchuanx/lession1.md
)都整理出来了，但是每一块都有很多内容，一周内该怎么去学习呢。跟着资料过一遍吗？

**Comment by miniflycn** [comment]
@if2er good，非常好。前面几节的基础课理论上为了快速帮大家把基础过一遍。如果前面这些内容一点都没有涉略，那就会非常幸苦。但自我学习应当要有重点，和有一定的节奏：

* 例如 addEventListener 和 事件标准 大家需要看吗？其实是可以不看的，除非你一直用React、Vue这种框架，否则应该都知道怎么用。
* 比如设计模式，其实可以了解下，但没有场景是难以深入的，所以需要的是知道，有印象，而不是现在就深入
* 比如Rxjs，其实市面上很少用，但是也需要知道
* 比如AJAX，大家应当有部分内容之前就知道，而不是等到现在才去学。

**Comment by Fridolph** [comment]
@if2er nice整理~ 让我借鉴copy下可好  想进行下二次加工 <img src="https://pic.sopili.net/pub/emoji/twitter/2/72x72/1f60b.png" width=20 height=20>

**Comment by Fridolph** [comment]
@miniflycn 老师，如您所说，2小时的课程就涉及了很多知识点，视频里的学习内容并没有太深入。自己看参考资料也是浅尝辄止。 <img src="https://pic.sopili.net/pub/emoji/twitter/2/72x72/1f914.png" width=20 height=20> 那怎么重点针对地进行学习和深入呢？

还有就是请教下 预习时和复习时的节奏 ~  其实写博客 我还是想写和课程相关的，这样感觉能巩固下，更有收益？~   问得有点杂，见谅 <img src="https://pic.sopili.net/pub/emoji/twitter/2/72x72/1f605.png" width=20 height=20>

**Comment by miniflycn** [comment]
@Fridolph 感觉我说怎么学没什么代表性，我要请几个同学来写写吧。

**Comment by Flcwl** [comment]
angular里面的中间人模式是不是就是发布订阅模式啊？如果不是，设计模式两者间有什么不同吗？
因为我认为两者都是为了实现两个组件间（或其它）的松耦合，通信由一个中介来负责。。

**Comment by yorts52** [comment]
@Flcwl 不一样, 这个是中介者模式
http://design-patterns.readthedocs.io/zh_CN/latest/behavioral_patterns/mediator.html#

**Comment by if2er** [comment]
@Fridolph 当然可以呀，我只是罗列上课老师讲课的内容，把一些案例加进去了，期待你的二次加工。

**Comment by yorts52** [comment]
@Flcwl 给出的链接有时序图和代码示例，你可以根据时序图和代码来看，区别还是很明显的，中介模式里面，通信是双向的，消息经过中介发送出去，并且接收方也可以是发送方。

**Comment by Flcwl** [comment]
```
// outer 包裹 inner标签
<div id = 'outer' style = 'margin: 100px 0 0 100px; width: 200px;height: 200px; background: red;'>
  <div id="inner" style = 'margin-left:20px; width: 50px;height:50px; background: green;'></div>
</div>
```

```
    var clickInner = document.getElementById('inner');
    var clickouter = document.getElementById('outer');
    clickInner.addEventListener('click', function() {
        alert('inner show');
        // event.stopPropagation();
    }, false);
    clickouter.addEventListener('click', function(e) {
        // alert('outer show');
        // console.log(e.target);
        e.stopPropagation();
        e.cancelBubble = true;
        alert(e.bubbles);  // 这里为什么一直是true？
        console.log(e.eventPhase);
        console.log(e.target);  // 事件委托
    }, true);
```
这段代码是否可以知道事件委托也可以发生在捕获阶段？
 因为所给的文章事件委托是用冒泡机制实现的， 

> 比如 focus、blur 之类的事件本身没有事件冒泡机制，所以无法委托；

  我想知道是否可以捕获阶段实现，虽然有点无聊哈。。望老师指点

**Comment by yorts52** [comment]
@Flcwl 这是一个好问题，上课的时候没有展开来讲

我把你上面的代码加到 [showcase9](https://github.com/FE-star/showcase9/blob/master/bubbles.html) 了，并且做了简单的调整

一、这里为什么一直是true？
> MDN 的文档已经有说明，如图
![image](https://user-images.githubusercontent.com/863697/41395264-99387a34-6fdf-11e8-8af3-704f7abe78c9.png)
这里的只读就是指这个属性是自产生的那一刻起就不会变了，决定这个值是 true 还是 false 的是 event 本身，有些事件是不冒泡的，参考这个 [wiki](https://en.wikipedia.org/wiki/DOM_events#Events)

二、这段代码是否可以知道事件委托也可以发生在捕获阶段？因为所给的文章事件委托是用冒泡机制实现的。
> 可以，一直以来习惯用冒泡来做事件委托最主要的原因是因为浏览器兼容问题，现在浏览器已经普遍支持捕获了，另外可以看看这个讨论 https://www.zhihu.com/question/39474653

三、比如 focus、blur 之类的事件本身没有事件冒泡机制，所以无法委托
> 我更倾向于这类事件并不需要冒泡，所以浏览器才会这么特殊处理

**Comment by miniflycn** [comment]
大家的讨论很有营养啊～

**Comment by asd2766** [comment]
观察者模式和订阅者模式具体运用场景是什么? 
1. 是不是其实我们在使用标签上的 onclick 事件的时候, 其实也是使用了观察者模式.
2. 在具体运用场景中, 哪些情况是可以使用这个模式的, 我现在虽然知道大概的概念, 但是对于使用场景却有点模糊.

**Comment by Flcwl** [comment]
@asd2766 具体场景应该有很多，比如天气变化立马给出相应的信息，通知穿什么样的衣服； 观察股票跌涨采取哪种措施？ github上有一个新的评论或讨论后我的邮箱会提醒我也是一种订阅哈啊哈

**Comment by yorts52** [comment]
@asd2766  可以看看 Node.js API Events
+ https://nodejs.org/api/events.html
+ https://github.com/nodejs/node/blob/master/lib/events.js
+ Node.js 里有大量的 API 是依赖 Events 的，这些都是其应用场景的体现

**Comment by zhangchch** [comment]
exercise17的pubsub类中，在订阅事件的时候，
1、有的同学，通过对象属性直接添加订阅事件
    `this.subscribers[type] =  fn;`

2、有的同学，先变成数组，然后通过数组添加订阅事件
    `this.subscribers[type].push(fn);`

请问这两种方式有什么区别，各有什么好处？

**Comment by zhuanyongxigua** [comment]
fetch的'no-cors'这个特性，可不可以用来csrf攻击？感觉即便返回的类型是opaque的，这个请求好像也是成功了啊。
