### ISSUE TITLE
第一节课问题收集

### ISSUE THREAD

**Issue by miniflycn** [FE-star/2018.6#7]
问题收集哈～大家多提问。

**Comment by if2er** [comment]
老师，你在课上讲的算法推荐课程是什么？好像在课上你忘记讲了。

**Comment by miniflycn** [comment]
@if2er CS61b

**Comment by miniflycn** [comment]
@asd2766 
答疑课解答下，但好像1我在正式课回答过？是没听到还是怎么样？

**Comment by zihudie** [comment]
1.老师能不能截取点平常工作中自己做的测试代码片段，让我们更直观的感受下。				
2.找了资料描述TDD的主要流程:先写测试，再写实现代码，然后不停的迭代重构，循环（自己实际工作没运用过对这个不是很理解）		
3.像很多业务逻辑糅杂的要怎么做测试呢？所有的场景都需要做测试吗，怎么划分哪些需要哪些不需要？		
4.增加写测试的时间会不会需要花费很多额外的时间精力，怎么把控时间进度节奏。

**Comment by miniflycn** [comment]
@zihudie 
1. 请看看 https://github.com/miniflycn/url-extract，或者看看阿里的egg是怎么测试的
2. 不理解指的是什么？
3. 代码逻辑耦合严重，这就考验你对代码的解耦能力了。并非所有场景需要，需要作出选择。
4. 还是那句话要有选择，测试能解决什么问题要心中有数哈

**Comment by if2er** [comment]
老大，关于这门课的学习方法问题，还是存在一点疑惑：

我现在是这么做的：
预习：
会跟着预习issue里提到的每个点，自己过一遍，大概弄清楚是什么东西，然后跟着exercise（如果有的话）用一遍或者过一遍，但是原理可能不是弄的不是很什么。

上课：
这时候因为内容太多，所以可能就是在预习的基础上把点串了起来，大概知道了是个什么东西，知道去哪里找资料深入了解，然后一般课程就结束了。

复习或者homework：
我会找个时候把视频回放一遍，整理出课程笔记。

但是问题是**其中涉及到的点，我们是不是应该在那一周时间内尽量弄清楚**，但是感觉这个量对于我个人来说有点多了，不知道这个情况是不是就是跟不上课程的意思。

还是说，每节课的内容只要弄懂个大概，明白自己不懂，但是要知道整个体系了有什么，自己懂哪些，不懂哪些，然后能够在日后复习的时候知道去哪里找资料补起来，就可以。

那进一步，这个timeline是什么时候，因为上次老师说不要等要用的时候采取学习，那意思就是说知道了哪些地方不懂，应该尽快在保证课程进度以及工作的前提下，自己找时间一定要尽快弄清楚是吗？

**Comment by zihudie** [comment]
@miniflycn  对于no.2 第二条的疑问，不是先写实现代码再去做测试吗？

**Comment by if2er** [comment]
老师，运行测试的时候如果想做断点调试的话怎么做？
